1.8
新增检测功能

diff --git a/.github/workflows/python-build.yaml b/.github/workflows/python-build.yaml
--- a/.github/workflows/python-build.yaml
+++ b/.github/workflows/python-build.yaml
@@ -46,6 +46,20 @@ jobs:
         run: |
           pyinstaller --onefile --hidden-import argparse --hidden-import pandas --hidden-import os --hidden-import tqdm --strip jtc-adh-cmd-plus.py --distpath dist/${{ matrix.os }}
 
+      - name: Run tests
+        run: |
+          python -m pip install pytest
+          pytest
+        
+      - name: Check tests
+        run: |
+          pytest --junitxml=pytest.xml
+          if grep -q 'failures="0" errors="0"' pytest.xml; then
+            echo "All tests passed"
+          else
+            echo "Some tests failed"
+            exit 1
+            
       - name: Upload-ubuntu-22.04
         if: ${{ matrix.os == 'ubuntu-22.04' }}
         uses: actions/upload-artifact@v3
